# Generated by Django 5.1.7 on 2025-04-01 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('comment', 'Comment'), ('club', 'Club'), ('club_activity', 'Club Activity'), ('county', 'County'), ('contact_message', 'Contact Message'), ('impact_metric', 'Impact Metric'), ('book_donation', 'Book Donation'), ('donation_pledge', 'Donation Pledge'), ('monetary_donation', 'Monetary Donation'), ('exchange', 'Exchange'), ('genre', 'Genre')], max_length=20)),
                ('action', models.CharField(choices=[('add', 'Add'), ('change', 'Change')], max_length=10)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
