# Generated by Django 5.1.7 on 2025-03-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial_list/')),
            ],
        ),
    ]
