# Generated by Django 5.1.7 on 2025-03-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
