# Generated by Django 5.1.7 on 2025-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='books/documents/'),
        ),
    ]
